### ISSUE TITLE
Remove --name parameter from frostfs-cli

### ISSUE THREAD

**Issue by ir0nbee** [TrueCloudLab/frostfs-node#37]
## Problem
The `--name` parameter implies setting a name for created container. However, this does not happen since the procedure was changed and requires setting special attributes with `--attributes` parameter. Thus the `--name` parameter and its description in command line help became misleading.

## Solution
1) Remove the `--name` parameter from command line.
2) Improve the documentation and make the information on setting container's name more accessible.

**Comment by realloc** [comment]
The attribute set by `--name` is [Name](https://github.com/TrueCloudLab/frostfs-api/blob/master/container/types.proto#L58), a non-unique human-friendly string.

Later we added NNS support, so special attributes [__NEOFS__NAME](https://github.com/TrueCloudLab/frostfs-api/blob/master/container/types.proto#L43) and [__NEOFS__ZONE](https://github.com/TrueCloudLab/frostfs-api/blob/master/container/types.proto#L46) should be set to register a container under a unique name in NNS.

I'd suggest adding a new argument, like `--nns-name` that would parse argument string and set one or both well-known attributes for NNS.
